name: Docker Image CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Record build time
      run: date +%s > time

    - name: Build the Docker container image
      run: docker build -t ghcr.io/timdeve/crystal-alpine/crystal-alpine:$(cat time) -t ghcr.io/timdeve/crystal-alpine/crystal-alpine:latest .
        
    - name: Push the image to GPR
      run: |
        echo $GITHUB_PACKAGE_REGISTRY_TOKEN | docker login ghcr.io -u TimDeve --password-stdin
        docker push ghcr.io/timdeve/crystal-alpine/crystal-alpine
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
