name: Docker Image CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Record build time
      run: date +%s > time

    - name: Build the Docker container image
      run: docker build -t docker.pkg.github.com/timdeve/crystal-alpine/crystal-alpine:$(cat time) .

    - name: Push the image to GPR
      run: |
        docker login docker.pkg.github.com -u TimDeve -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
        docker push docker.pkg.github.com/timdeve/crystal-alpine/crystal-alpine:$(cat time)
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
